### ISSUE TITLE
No value has been specified for property 'sonatypePassword'

### ISSUE THREAD

**Issue by tinesoft** [nebula-plugins/nebula-bintray-plugin#35]
Hi Nebula team!

I having trouble using this great plugin to publish my artifacts to Bintray using Travis CI, in particular during the **syncVersionToMavenCentral** phase (everything prior works fine).

I kept having this error:
> No value has been specified for property 'sonatypePassword'.

(_see [full travis log](https://travis-ci.org/tinesoft/spring-esdata-loader/builds/565304951)_):

My `bintray` configuration object looks like this:

```
apply plugin: "nebula.nebula-bintray"

bintray {
  user = project.bintrayUsername ?: "tinesoft"
  apiKey = project.bintrayKey

  repo = "maven"
  userOrg = "tinesoft"
  description = "Set of JUnit Rule & Extension to easily load data to test your spring-data elasticsearch-based projects"
  websiteUrl = "https://github.com/tinesoft/spring-esdata-loader"
  issueTrackerUrl = "https://github.com/tinesoft/spring-esdata-loader/issues"
  vcsUrl = "https://github.com/tinesoft/spring-esdata-loader.git"
  licenses = ["MIT"]
  labels = ["spring-data-elasticsearch", "elasticsearch", "junit4", "junit-jupiter", "testing", "testing", "integration-test"]
}

```

The credentials are set like this:
```
def setExtValue(String property, String systemEnv) {
  project.ext."$property" = project.hasProperty(property) ? project.getProperty(property) : System.getenv(systemEnv)
}

setExtValue('bintrayUsername', 'BINTRAY_USER')
setExtValue('bintrayKey', 'BINTRAY_KEY')
setExtValue('ghToken', 'GH_TOKEN')
setExtValue('sonatypeUsername', 'SONATYPE_USERNAME')
setExtValue('sonatypePassword', 'SONATYPE_PASSWORD ')
````
(_see whole project here: https://github.com/tinesoft/spring-esdata-loader_)

**$SONATYPE_USERNAME** and **$SONATYPE_PASSWORD** are secured environment variables in the `.travis.yml` file, and are correctly picked up, as you can see in the beginning of Travis job log mentioned above.

A couple of precisions:
- my sonatype username/password are valid (i can connect to Nexus OSS)
- my groupId (com.github.tinesoft) [has been activated](https://issues.sonatype.org/browse/OSSRH-50241#) by Nexus team 
- the upload to Bintray part worked (see [files](https://bintray.com/tinesoft/maven/spring-esdata-loader-core#files/com/github/tinesoft/spring-esdata-loader-core))
- i tried to directly provide credentials via command line `./gradlew -Prelease.travisci=true -Prelease.useLastTag=true -Psonatype.username=$SONATYPE_USERNAME -Psonatype.password=$SONATYPE_PASSWORD final ` but still fails...

**Comment by tinesoft** [comment]
Moreover, looking at https://github.com/nebula-plugins/nebula-bintray-plugin/blob/38dd155c41466e880ffce2c791a4ae1cca4f54e8/src/main/kotlin/nebula/plugin/bintray/NebulaBintrayPublishingPlugin.kt#L144
i noticed that the **bintray.sonatypeUsername** and **bintray.sonatypePassword** properties **have no default values** like the other properties of the `BintrayExtension.kt`

Could this be why the validation fails?

**Comment by chali** [comment]
Hi, @tinesoft I would say the empty defaults should not play a role in the failure. This part is supposed to read project properties or environment properties and set extension values which are later used of the sync task which failed.

I would try those actions:

I noticed that you have a space after `SONATYPE_PASSWORD` on this line.
`setExtValue('sonatypePassword', 'SONATYPE_PASSWORD ')` I would try `setExtValue('sonatypePassword', 'SONATYPE_PASSWORD')`

If that is not the reason I would try this way of passing the parameters:
```
bintray {
  sonatypeUsername = project.sonatypeUsername
  sonatypePassword = project.sonatypePassword
}
```

As the last attempt, I would try to run the same build on a local machine and debug this part https://github.com/nebula-plugins/nebula-bintray-plugin/blob/38dd155c41466e880ffce2c791a4ae1cca4f54e8/src/main/kotlin/nebula/plugin/bintray/NebulaBintrayPublishingPlugin.kt#L181-L197

**Comment by tinesoft** [comment]
Good catch!
 
That extra space in `setExtValue('sonatypePassword', 'SONATYPE_PASSWORD ') ` was indeed the what caused the problem. 

Thank you for your help!
